//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCIOfficeServiceManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirtelManagement
    {
        public long Id { get; set; }
        public long AccountNo { get; set; }
        public long AirtelNumber { get; set; }
        public double OnetimeCharges { get; set; }
        public double MonthlyCharges { get; set; }
        public double CallCharges { get; set; }
        public double ValueAddedServices { get; set; }
        public double MobileInternetUsage { get; set; }
        public double Roaming { get; set; }
        public double Discounts { get; set; }
        public double Taxes { get; set; }
        public double TotalCharges { get; set; }
        public string WhoUploaded { get; set; }
        public System.DateTime UploadedDate { get; set; }
        public System.DateTime ForWhichMonth { get; set; }
    }
}
